/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.AlternateTitle;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.Genre;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.Manhwa;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.ManhwaGenre;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.ManhwaTag;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.RelatedManhwa;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.Tag;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.TitleLanguage;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManhwaNexus extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>manhwa_nexus</code>
     */
    public static final ManhwaNexus MANHWA_NEXUS = new ManhwaNexus();

    /**
     * The table <code>manhwa_nexus.alternate_title</code>.
     */
    public final AlternateTitle ALTERNATE_TITLE = AlternateTitle.ALTERNATE_TITLE;

    /**
     * The table <code>manhwa_nexus.genre</code>.
     */
    public final Genre GENRE = Genre.GENRE;

    /**
     * The table <code>manhwa_nexus.manhwa</code>.
     */
    public final Manhwa MANHWA = Manhwa.MANHWA;

    /**
     * The table <code>manhwa_nexus.manhwa_genre</code>.
     */
    public final ManhwaGenre MANHWA_GENRE = ManhwaGenre.MANHWA_GENRE;

    /**
     * The table <code>manhwa_nexus.manhwa_tag</code>.
     */
    public final ManhwaTag MANHWA_TAG = ManhwaTag.MANHWA_TAG;

    /**
     * The table <code>manhwa_nexus.related_manhwa</code>.
     */
    public final RelatedManhwa RELATED_MANHWA = RelatedManhwa.RELATED_MANHWA;

    /**
     * The table <code>manhwa_nexus.tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * The table <code>manhwa_nexus.title_language</code>.
     */
    public final TitleLanguage TITLE_LANGUAGE = TitleLanguage.TITLE_LANGUAGE;

    /**
     * No further instances allowed
     */
    private ManhwaNexus() {
        super("manhwa_nexus", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AlternateTitle.ALTERNATE_TITLE,
            Genre.GENRE,
            Manhwa.MANHWA,
            ManhwaGenre.MANHWA_GENRE,
            ManhwaTag.MANHWA_TAG,
            RelatedManhwa.RELATED_MANHWA,
            Tag.TAG,
            TitleLanguage.TITLE_LANGUAGE
        );
    }
}
