/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.AlternateTitle;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.Genre;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.Manhwa;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.ManhwaGenre;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.ManhwaTag;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.RelatedManhwa;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.Tag;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.TitleLanguage;


/**
 * Convenience access to all tables in manhwa_nexus.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>manhwa_nexus.alternate_title</code>.
     */
    public static final AlternateTitle ALTERNATE_TITLE = AlternateTitle.ALTERNATE_TITLE;

    /**
     * The table <code>manhwa_nexus.genre</code>.
     */
    public static final Genre GENRE = Genre.GENRE;

    /**
     * The table <code>manhwa_nexus.manhwa</code>.
     */
    public static final Manhwa MANHWA = Manhwa.MANHWA;

    /**
     * The table <code>manhwa_nexus.manhwa_genre</code>.
     */
    public static final ManhwaGenre MANHWA_GENRE = ManhwaGenre.MANHWA_GENRE;

    /**
     * The table <code>manhwa_nexus.manhwa_tag</code>.
     */
    public static final ManhwaTag MANHWA_TAG = ManhwaTag.MANHWA_TAG;

    /**
     * The table <code>manhwa_nexus.related_manhwa</code>.
     */
    public static final RelatedManhwa RELATED_MANHWA = RelatedManhwa.RELATED_MANHWA;

    /**
     * The table <code>manhwa_nexus.tag</code>.
     */
    public static final Tag TAG = Tag.TAG;

    /**
     * The table <code>manhwa_nexus.title_language</code>.
     */
    public static final TitleLanguage TITLE_LANGUAGE = TitleLanguage.TITLE_LANGUAGE;
}
