DROP SCHEMA IF EXISTS manhwa_nexus CASCADE;
CREATE SCHEMA IF NOT EXISTS manhwa_nexus;
SET SCHEMA 'manhwa_nexus';

-- Types
DROP TYPE IF EXISTS SOURCE_MATERIAL;
CREATE TYPE SOURCE_MATERIAL AS ENUM ('ORIGINAL', 'LIGHT_NOVEL', 'WEB_NOVEL', 'VIDEO_GAME', 'OTHER', 'VISUAL_NOVEL');

-- Domains
-- TODO: Add domains with constraints

-- Tables
--TODO: Add table for studios, publishers, staff
DROP TABLE IF EXISTS title_language CASCADE;
CREATE TABLE IF NOT EXISTS title_language
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language varchar(2)
);

DROP TABLE IF EXISTS manhwa CASCADE;
CREATE TABLE IF NOT EXISTS manhwa
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                varchar(200) NOT NULL,
    synopsis             varchar(2000),
    chapter_count        INT,
    volume_count         INT,
    season_count         INT,
    start_date           DATE,
    end_date             DATE,
    is_adult             BOOLEAN,
    source_material      SOURCE_MATERIAL,
    country_of_origin_id INT,
    cover_url VARCHAR(2000),
    status VARCHAR(2000),
    FOREIGN KEY (country_of_origin_id) REFERENCES title_language (id)
);

DROP TABLE IF EXISTS manhwa CASCADE;
CREATE TABLE IF NOT EXISTS character
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100),
    age         INT,
    race        VARCHAR(100),
    occupation  VARCHAR(200),
    status      VARCHAR(50),
    description varchar(2000),
    manhwa_id   INT,
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id)
);

DROP TABLE IF EXISTS character_title CASCADE;
CREATE TABLE IF NOT EXISTS character_title
(
    character_id INT,
    title        VARCHAR(200),
    PRIMARY KEY (character_id, title),
    FOREIGN KEY (character_id) REFERENCES character (id)
);

DROP TABLE IF EXISTS character_relative CASCADE;
CREATE TABLE IF NOT EXISTS character_relative
(
    character_id INT,
    relative_id  INT,
    PRIMARY KEY (character_id, relative_id),
    FOREIGN KEY (character_id) REFERENCES character (id),
    FOREIGN KEY (relative_id) REFERENCES character (id)
);

DROP TABLE IF EXISTS genre CASCADE;
CREATE TABLE IF NOT EXISTS genre
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre varchar(50)
);

DROP TABLE IF EXISTS tag CASCADE;
CREATE TABLE IF NOT EXISTS tag
(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag varchar(100)
);

DROP TABLE IF EXISTS manhwa_genre CASCADE;
CREATE TABLE IF NOT EXISTS manhwa_genre
(
    manhwa_id INT,
    genre_id  INT,
    PRIMARY KEY (manhwa_id, genre_id),
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id),
    FOREIGN KEY (genre_id) REFERENCES genre (id)
);

DROP TABLE IF EXISTS manhwa_tag CASCADE;
CREATE TABLE IF NOT EXISTS manhwa_tag
(
    manhwa_id INT,
    tag_id    INT,
    PRIMARY KEY (manhwa_id, tag_id),
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id),
    FOREIGN KEY (tag_id) REFERENCES tag (id)
);

DROP TABLE IF EXISTS related_manhwa CASCADE;
CREATE TABLE IF NOT EXISTS related_manhwa
(
    manhwa1_id INT,
    manhwa2_id INT,
    PRIMARY KEY (manhwa1_id, manhwa2_id),
    FOREIGN KEY (manhwa1_id) REFERENCES manhwa (id),
    FOREIGN KEY (manhwa2_id) REFERENCES manhwa (id)
);


DROP TABLE IF EXISTS alternate_title CASCADE;
CREATE TABLE IF NOT EXISTS alternate_title
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_language_id INT,
    manhwa_id         INT,
    title             varchar(200),
    FOREIGN KEY (title_language_id) REFERENCES title_language (id),
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id)
);

DROP TABLE IF EXISTS country_code CASCADE;
CREATE TABLE IF NOT EXISTS country_code
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(2)
);

DROP TABLE IF EXISTS studio CASCADE;
CREATE TABLE IF NOT EXISTS studio
(
    id                   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(100),
    official_website_url VARCHAR(300)
);

DROP TABLE IF EXISTS studio_work CASCADE;
CREATE TABLE IF NOT EXISTS studio_work
(
    studio_id INT,
    manhwa_id INT,
    PRIMARY KEY (studio_id, manhwa_id),
    FOREIGN KEY (studio_id) REFERENCES studio (id),
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id)
);


DROP TABLE IF EXISTS publisher CASCADE;
CREATE TABLE IF NOT EXISTS publisher
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100)
);

DROP TABLE IF EXISTS publisher_work CASCADE;
CREATE TABLE IF NOT EXISTS publisher_work
(
    publisher_id INT,
    manhwa_id    INT,
    PRIMARY KEY (publisher_id, manhwa_id),
    FOREIGN KEY (publisher_id) REFERENCES publisher (id),
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id)
);

-- INIT KNOWN VALUES
---- COUNTRY CODES
INSERT INTO country_code (code)
VALUES ('DK');
INSERT INTO country_code (code)
VALUES ('KR');
INSERT INTO country_code (code)
VALUES ('JP');
INSERT INTO country_code (code)
VALUES ('GB');
INSERT INTO country_code (code)
VALUES ('US');

---- TITLE LANGUAGES
INSERT INTO title_language(language)
VALUES ('EN');
INSERT INTO title_language(language)
VALUES ('JP');
INSERT INTO title_language(language)
VALUES ('KR');

---- GENRES
INSERT INTO genre(genre)
VALUES ('Romance');
INSERT INTO genre(genre)
VALUES ('Action');
INSERT INTO genre(genre)
VALUES ('Comedy');
INSERT INTO genre(genre)
VALUES ('Rom-Com');
INSERT INTO genre(genre)
VALUES ('Fantasy');
INSERT INTO genre(genre)
VALUES ('Sci-Fi');
INSERT INTO genre(genre)
VALUES ('Horror');
INSERT INTO genre(genre)
VALUES ('Drama');
INSERT INTO genre(genre)
VALUES ('Adventure');
INSERT INTO genre(genre)
VALUES ('Mystery');
INSERT INTO genre(genre)
VALUES ('Psychological');
INSERT INTO genre(genre)
VALUES ('Ecchi');
INSERT INTO genre(genre)
VALUES ('Sports');
INSERT INTO genre(genre)
VALUES ('Thriller');
INSERT INTO genre(genre)
VALUES ('Supernatural');
INSERT INTO genre(genre)
VALUES ('Music');
INSERT INTO genre(genre)
VALUES ('Mecha');
INSERT INTO genre(genre)
VALUES ('Slice of Life');
