DROP SCHEMA IF EXISTS manhwa_nexus CASCADE;
CREATE SCHEMA manhwa_nexus;
SET SCHEMA 'manhwa_nexus';

-- Domains
-- TODO: Add domains with constraints

-- Tables
--TODO: Add table for characters, studios, publishers, staff, source material
CREATE TABLE IF NOT EXISTS manhwa
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         varchar(200) NOT NULL,
    synopsis      varchar(2000),
    chapter_count INT,
    volume_count  INT,
    season_count  INT,
    start_date    DATE,
    end_date      DATE,
    is_adult      BOOLEAN
);

CREATE TABLE IF NOT EXISTS genre
(
    id    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre varchar(50)
);

CREATE TABLE IF NOT EXISTS tag
(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag varchar(100)
);

CREATE TABLE IF NOT EXISTS manhwa_genre
(
    manhwa_id INT,
    genre_id  INT,
    PRIMARY KEY (manhwa_id, genre_id),
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id),
    FOREIGN KEY (genre_id) REFERENCES genre (id)
);

CREATE TABLE IF NOT EXISTS manhwa_tag
(
    manhwa_id INT,
    tag_id    INT,
    PRIMARY KEY (manhwa_id, tag_id),
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id),
    FOREIGN KEY (tag_id) REFERENCES tag (id)
);

CREATE TABLE IF NOT EXISTS related_manhwa
(
    manhwa1_id INT,
    manhwa2_id INT,
    PRIMARY KEY (manhwa1_id, manhwa2_id),
    FOREIGN KEY (manhwa1_id) REFERENCES manhwa (id),
    FOREIGN KEY (manhwa2_id) REFERENCES manhwa (id)
);

CREATE TABLE IF NOT EXISTS title_language
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language varchar(2)
);

CREATE TABLE IF NOT EXISTS alternate_title
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_language_id INT,
    manhwa_id         INT,
    title             varchar(200),
    FOREIGN KEY (title_language_id) REFERENCES title_language (id),
    FOREIGN KEY (manhwa_id) REFERENCES manhwa (id)
);

