/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.records;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.AlternateTitle;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlternateTitleRecord extends UpdatableRecordImpl<AlternateTitleRecord> implements Record4<Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manhwa_nexus.alternate_title.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>manhwa_nexus.alternate_title.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manhwa_nexus.alternate_title.title_language_id</code>.
     */
    public void setTitleLanguageId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>manhwa_nexus.alternate_title.title_language_id</code>.
     */
    public Integer getTitleLanguageId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>manhwa_nexus.alternate_title.manhwa_id</code>.
     */
    public void setManhwaId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>manhwa_nexus.alternate_title.manhwa_id</code>.
     */
    public Integer getManhwaId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>manhwa_nexus.alternate_title.title</code>.
     */
    public void setTitle(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>manhwa_nexus.alternate_title.title</code>.
     */
    public String getTitle() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, Integer, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, Integer, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AlternateTitle.ALTERNATE_TITLE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AlternateTitle.ALTERNATE_TITLE.TITLE_LANGUAGE_ID;
    }

    @Override
    public Field<Integer> field3() {
        return AlternateTitle.ALTERNATE_TITLE.MANHWA_ID;
    }

    @Override
    public Field<String> field4() {
        return AlternateTitle.ALTERNATE_TITLE.TITLE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getTitleLanguageId();
    }

    @Override
    public Integer component3() {
        return getManhwaId();
    }

    @Override
    public String component4() {
        return getTitle();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getTitleLanguageId();
    }

    @Override
    public Integer value3() {
        return getManhwaId();
    }

    @Override
    public String value4() {
        return getTitle();
    }

    @Override
    public AlternateTitleRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AlternateTitleRecord value2(Integer value) {
        setTitleLanguageId(value);
        return this;
    }

    @Override
    public AlternateTitleRecord value3(Integer value) {
        setManhwaId(value);
        return this;
    }

    @Override
    public AlternateTitleRecord value4(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public AlternateTitleRecord values(Integer value1, Integer value2, Integer value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlternateTitleRecord
     */
    public AlternateTitleRecord() {
        super(AlternateTitle.ALTERNATE_TITLE);
    }

    /**
     * Create a detached, initialised AlternateTitleRecord
     */
    public AlternateTitleRecord(Integer id, Integer titleLanguageId, Integer manhwaId, String title) {
        super(AlternateTitle.ALTERNATE_TITLE);

        setId(id);
        setTitleLanguageId(titleLanguageId);
        setManhwaId(manhwaId);
        setTitle(title);
    }
}
