/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.records;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.ManhwaGenre;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManhwaGenreRecord extends UpdatableRecordImpl<ManhwaGenreRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manhwa_nexus.manhwa_genre.manhwa_id</code>.
     */
    public void setManhwaId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa_genre.manhwa_id</code>.
     */
    public Integer getManhwaId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa_genre.genre_id</code>.
     */
    public void setGenreId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa_genre.genre_id</code>.
     */
    public Integer getGenreId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ManhwaGenre.MANHWA_GENRE.MANHWA_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ManhwaGenre.MANHWA_GENRE.GENRE_ID;
    }

    @Override
    public Integer component1() {
        return getManhwaId();
    }

    @Override
    public Integer component2() {
        return getGenreId();
    }

    @Override
    public Integer value1() {
        return getManhwaId();
    }

    @Override
    public Integer value2() {
        return getGenreId();
    }

    @Override
    public ManhwaGenreRecord value1(Integer value) {
        setManhwaId(value);
        return this;
    }

    @Override
    public ManhwaGenreRecord value2(Integer value) {
        setGenreId(value);
        return this;
    }

    @Override
    public ManhwaGenreRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManhwaGenreRecord
     */
    public ManhwaGenreRecord() {
        super(ManhwaGenre.MANHWA_GENRE);
    }

    /**
     * Create a detached, initialised ManhwaGenreRecord
     */
    public ManhwaGenreRecord(Integer manhwaId, Integer genreId) {
        super(ManhwaGenre.MANHWA_GENRE);

        setManhwaId(manhwaId);
        setGenreId(genreId);
    }
}
