/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.records;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.Manhwa;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManhwaRecord extends UpdatableRecordImpl<ManhwaRecord> implements Record9<Integer, String, String, Integer, Integer, Integer, LocalDate, LocalDate, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manhwa_nexus.manhwa.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa.synopsis</code>.
     */
    public void setSynopsis(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.synopsis</code>.
     */
    public String getSynopsis() {
        return (String) get(2);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa.chapter_count</code>.
     */
    public void setChapterCount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.chapter_count</code>.
     */
    public Integer getChapterCount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa.volume_count</code>.
     */
    public void setVolumeCount(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.volume_count</code>.
     */
    public Integer getVolumeCount() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa.season_count</code>.
     */
    public void setSeasonCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.season_count</code>.
     */
    public Integer getSeasonCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa.start_date</code>.
     */
    public void setStartDate(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.start_date</code>.
     */
    public LocalDate getStartDate() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa.end_date</code>.
     */
    public void setEndDate(LocalDate value) {
        set(7, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.end_date</code>.
     */
    public LocalDate getEndDate() {
        return (LocalDate) get(7);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa.is_adult</code>.
     */
    public void setIsAdult(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa.is_adult</code>.
     */
    public Boolean getIsAdult() {
        return (Boolean) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Integer, String, String, Integer, Integer, Integer, LocalDate, LocalDate, Boolean> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Integer, String, String, Integer, Integer, Integer, LocalDate, LocalDate, Boolean> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Manhwa.MANHWA.ID;
    }

    @Override
    public Field<String> field2() {
        return Manhwa.MANHWA.TITLE;
    }

    @Override
    public Field<String> field3() {
        return Manhwa.MANHWA.SYNOPSIS;
    }

    @Override
    public Field<Integer> field4() {
        return Manhwa.MANHWA.CHAPTER_COUNT;
    }

    @Override
    public Field<Integer> field5() {
        return Manhwa.MANHWA.VOLUME_COUNT;
    }

    @Override
    public Field<Integer> field6() {
        return Manhwa.MANHWA.SEASON_COUNT;
    }

    @Override
    public Field<LocalDate> field7() {
        return Manhwa.MANHWA.START_DATE;
    }

    @Override
    public Field<LocalDate> field8() {
        return Manhwa.MANHWA.END_DATE;
    }

    @Override
    public Field<Boolean> field9() {
        return Manhwa.MANHWA.IS_ADULT;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public String component3() {
        return getSynopsis();
    }

    @Override
    public Integer component4() {
        return getChapterCount();
    }

    @Override
    public Integer component5() {
        return getVolumeCount();
    }

    @Override
    public Integer component6() {
        return getSeasonCount();
    }

    @Override
    public LocalDate component7() {
        return getStartDate();
    }

    @Override
    public LocalDate component8() {
        return getEndDate();
    }

    @Override
    public Boolean component9() {
        return getIsAdult();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public String value3() {
        return getSynopsis();
    }

    @Override
    public Integer value4() {
        return getChapterCount();
    }

    @Override
    public Integer value5() {
        return getVolumeCount();
    }

    @Override
    public Integer value6() {
        return getSeasonCount();
    }

    @Override
    public LocalDate value7() {
        return getStartDate();
    }

    @Override
    public LocalDate value8() {
        return getEndDate();
    }

    @Override
    public Boolean value9() {
        return getIsAdult();
    }

    @Override
    public ManhwaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ManhwaRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public ManhwaRecord value3(String value) {
        setSynopsis(value);
        return this;
    }

    @Override
    public ManhwaRecord value4(Integer value) {
        setChapterCount(value);
        return this;
    }

    @Override
    public ManhwaRecord value5(Integer value) {
        setVolumeCount(value);
        return this;
    }

    @Override
    public ManhwaRecord value6(Integer value) {
        setSeasonCount(value);
        return this;
    }

    @Override
    public ManhwaRecord value7(LocalDate value) {
        setStartDate(value);
        return this;
    }

    @Override
    public ManhwaRecord value8(LocalDate value) {
        setEndDate(value);
        return this;
    }

    @Override
    public ManhwaRecord value9(Boolean value) {
        setIsAdult(value);
        return this;
    }

    @Override
    public ManhwaRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Integer value6, LocalDate value7, LocalDate value8, Boolean value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManhwaRecord
     */
    public ManhwaRecord() {
        super(Manhwa.MANHWA);
    }

    /**
     * Create a detached, initialised ManhwaRecord
     */
    public ManhwaRecord(Integer id, String title, String synopsis, Integer chapterCount, Integer volumeCount, Integer seasonCount, LocalDate startDate, LocalDate endDate, Boolean isAdult) {
        super(Manhwa.MANHWA);

        setId(id);
        setTitle(title);
        setSynopsis(synopsis);
        setChapterCount(chapterCount);
        setVolumeCount(volumeCount);
        setSeasonCount(seasonCount);
        setStartDate(startDate);
        setEndDate(endDate);
        setIsAdult(isAdult);
    }
}
