/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.records;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.ManhwaTag;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManhwaTagRecord extends UpdatableRecordImpl<ManhwaTagRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manhwa_nexus.manhwa_tag.manhwa_id</code>.
     */
    public void setManhwaId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa_tag.manhwa_id</code>.
     */
    public Integer getManhwaId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manhwa_nexus.manhwa_tag.tag_id</code>.
     */
    public void setTagId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>manhwa_nexus.manhwa_tag.tag_id</code>.
     */
    public Integer getTagId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return ManhwaTag.MANHWA_TAG.MANHWA_ID;
    }

    @Override
    public Field<Integer> field2() {
        return ManhwaTag.MANHWA_TAG.TAG_ID;
    }

    @Override
    public Integer component1() {
        return getManhwaId();
    }

    @Override
    public Integer component2() {
        return getTagId();
    }

    @Override
    public Integer value1() {
        return getManhwaId();
    }

    @Override
    public Integer value2() {
        return getTagId();
    }

    @Override
    public ManhwaTagRecord value1(Integer value) {
        setManhwaId(value);
        return this;
    }

    @Override
    public ManhwaTagRecord value2(Integer value) {
        setTagId(value);
        return this;
    }

    @Override
    public ManhwaTagRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManhwaTagRecord
     */
    public ManhwaTagRecord() {
        super(ManhwaTag.MANHWA_TAG);
    }

    /**
     * Create a detached, initialised ManhwaTagRecord
     */
    public ManhwaTagRecord(Integer manhwaId, Integer tagId) {
        super(ManhwaTag.MANHWA_TAG);

        setManhwaId(manhwaId);
        setTagId(tagId);
    }
}
