/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.records;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.RelatedManhwa;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RelatedManhwaRecord extends UpdatableRecordImpl<RelatedManhwaRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manhwa_nexus.related_manhwa.manhwa1_id</code>.
     */
    public void setManhwa1Id(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>manhwa_nexus.related_manhwa.manhwa1_id</code>.
     */
    public Integer getManhwa1Id() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manhwa_nexus.related_manhwa.manhwa2_id</code>.
     */
    public void setManhwa2Id(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>manhwa_nexus.related_manhwa.manhwa2_id</code>.
     */
    public Integer getManhwa2Id() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return RelatedManhwa.RELATED_MANHWA.MANHWA1_ID;
    }

    @Override
    public Field<Integer> field2() {
        return RelatedManhwa.RELATED_MANHWA.MANHWA2_ID;
    }

    @Override
    public Integer component1() {
        return getManhwa1Id();
    }

    @Override
    public Integer component2() {
        return getManhwa2Id();
    }

    @Override
    public Integer value1() {
        return getManhwa1Id();
    }

    @Override
    public Integer value2() {
        return getManhwa2Id();
    }

    @Override
    public RelatedManhwaRecord value1(Integer value) {
        setManhwa1Id(value);
        return this;
    }

    @Override
    public RelatedManhwaRecord value2(Integer value) {
        setManhwa2Id(value);
        return this;
    }

    @Override
    public RelatedManhwaRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RelatedManhwaRecord
     */
    public RelatedManhwaRecord() {
        super(RelatedManhwa.RELATED_MANHWA);
    }

    /**
     * Create a detached, initialised RelatedManhwaRecord
     */
    public RelatedManhwaRecord(Integer manhwa1Id, Integer manhwa2Id) {
        super(RelatedManhwa.RELATED_MANHWA);

        setManhwa1Id(manhwa1Id);
        setManhwa2Id(manhwa2Id);
    }
}
