/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.records;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.TitleLanguage;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TitleLanguageRecord extends UpdatableRecordImpl<TitleLanguageRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>manhwa_nexus.title_language.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>manhwa_nexus.title_language.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>manhwa_nexus.title_language.language</code>.
     */
    public void setLanguage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>manhwa_nexus.title_language.language</code>.
     */
    public String getLanguage() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TitleLanguage.TITLE_LANGUAGE.ID;
    }

    @Override
    public Field<String> field2() {
        return TitleLanguage.TITLE_LANGUAGE.LANGUAGE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLanguage();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLanguage();
    }

    @Override
    public TitleLanguageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TitleLanguageRecord value2(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public TitleLanguageRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TitleLanguageRecord
     */
    public TitleLanguageRecord() {
        super(TitleLanguage.TITLE_LANGUAGE);
    }

    /**
     * Create a detached, initialised TitleLanguageRecord
     */
    public TitleLanguageRecord(Integer id, String language) {
        super(TitleLanguage.TITLE_LANGUAGE);

        setId(id);
        setLanguage(language);
    }
}
