/*
 * This file is generated by jOOQ.
 */
package io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables;


import io.github.michaelbui99.manhwanexus.dataaccess.codegen.Keys;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.ManhwaNexus;
import io.github.michaelbui99.manhwanexus.dataaccess.codegen.tables.records.TitleLanguageRecord;

import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function2;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TitleLanguage extends TableImpl<TitleLanguageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>manhwa_nexus.title_language</code>
     */
    public static final TitleLanguage TITLE_LANGUAGE = new TitleLanguage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TitleLanguageRecord> getRecordType() {
        return TitleLanguageRecord.class;
    }

    /**
     * The column <code>manhwa_nexus.title_language.id</code>.
     */
    public final TableField<TitleLanguageRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>manhwa_nexus.title_language.language</code>.
     */
    public final TableField<TitleLanguageRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.VARCHAR(2), this, "");

    private TitleLanguage(Name alias, Table<TitleLanguageRecord> aliased) {
        this(alias, aliased, null);
    }

    private TitleLanguage(Name alias, Table<TitleLanguageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>manhwa_nexus.title_language</code> table
     * reference
     */
    public TitleLanguage(String alias) {
        this(DSL.name(alias), TITLE_LANGUAGE);
    }

    /**
     * Create an aliased <code>manhwa_nexus.title_language</code> table
     * reference
     */
    public TitleLanguage(Name alias) {
        this(alias, TITLE_LANGUAGE);
    }

    /**
     * Create a <code>manhwa_nexus.title_language</code> table reference
     */
    public TitleLanguage() {
        this(DSL.name("title_language"), null);
    }

    public <O extends Record> TitleLanguage(Table<O> child, ForeignKey<O, TitleLanguageRecord> key) {
        super(child, key, TITLE_LANGUAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : ManhwaNexus.MANHWA_NEXUS;
    }

    @Override
    public Identity<TitleLanguageRecord, Integer> getIdentity() {
        return (Identity<TitleLanguageRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<TitleLanguageRecord> getPrimaryKey() {
        return Keys.TITLE_LANGUAGE_PKEY;
    }

    @Override
    public TitleLanguage as(String alias) {
        return new TitleLanguage(DSL.name(alias), this);
    }

    @Override
    public TitleLanguage as(Name alias) {
        return new TitleLanguage(alias, this);
    }

    @Override
    public TitleLanguage as(Table<?> alias) {
        return new TitleLanguage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TitleLanguage rename(String name) {
        return new TitleLanguage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TitleLanguage rename(Name name) {
        return new TitleLanguage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TitleLanguage rename(Table<?> name) {
        return new TitleLanguage(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function2<? super Integer, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
